# Data loaded

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_pickle('../dataset/SS/clean/filtered_data.pkl')

In [39]:
data_sample = df.sample(frac=0.01, random_state=1)

In [40]:
data_sample.head()

title  \
paper_id                                                      
7786925                        Temporal reachability graphs   
7231337   Enhancing Language Models in Statistical Machi...   
18372073                 Bundle recommendation in ecommerce   
17857735    Extending Recognition in a Changing Environment   
14145146  Type-driven Development of Concurrent Communic...   

                                                   abstract  \
paper_id                                                      
7786925   While a natural fit for modeling and understan...   
7231337   In this paper, with a belief that a language m...   
18372073  Recommender system has become an important com...   
17857735  We consider the task of visual recognition of ...   
14145146  Abstract Modern software systems rely on commu...   

                                                  full_text  \
paper_id                                                      
7786925   While a natural fit for modeling and understan...   
7231337   In this paper, with a belief that a language m...   
18372073  Recommender system has become an important com...   
17857735  We consider the task of visual recognition of ...   
14145146  Abstract Modern software systems rely on commu...   

                                                  body_text  \
paper_id                                                      
7786925   Permission to make digital or hard copies of a...   
7231337   Language model is one of the most important kn...   
18372073  Recommender system is one of the key component...   
17857735  The world around us is a dynamic environment, ...   
14145146  Implementing communicating concurrent systems ...   

                                          related_work_text  \
paper_id                                                      
7786925   Adaptations of traditional static graph distan...   
7231337   Previous work devoted to improving language mo...   
18372073  Recommender system has attracted a lot of atte...   
17857735  We follow the paradigm of detecting and locali...   
14145146  The Idris virtual machine has message passing ...   

                                         related_work_pairs  \
paper_id                                                      
7786925   {'2910521': 'TVGs based on different waiting p...   
7231337   {'1345384': 'Since the context "history" in th...   
18372073  {'207178809': 'Recommender system has attracte...   
17857735  {'5264115': 'Epshtein and Ullman, 2007; Felzen...   
14145146  {'2328392': 'The Idris virtual machine has mes...   

                                                 body_pairs  
paper_id                                                     
7786925   {'4429113': 'Alternatively called temporal net...  
7231337   {'13259913': 'Language model is one of the mos...  
18372073  {'12438860': "It allows eCommerce company to p...  
17857735  {'1143910': 'For efficiency we use approximate...  
14145146  {'6038950': "In this paper, I describe a type-...

In [41]:
len(data_sample)

229

# Lex Rank

In [ ]:
### run this cell at first time
# !pip install sumy
# import nltk
# nltk.download('punkt')

In [6]:
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer

In [7]:
def lexrank(text, n):
    # text: a plaintext to generate summary of
    # n: number of sentences in the summary
    my_parser = PlaintextParser.from_string(text, Tokenizer('english'))
    lexrank_summarizer = LexRankSummarizer()
    lexrank_summary = lexrank_summarizer(my_parser.document, sentences_count=n)
    
    res = ''
    for sentence in lexrank_summary:
        res = res + ' ' + str(sentence)
        
    return res

In [ ]:
test_text='Junk foods taste good that’s why it is mostly liked by everyone of any age group especially kids and school going children. They generally ask for the junk food daily because they have been trend so by their parents from the childhood. They never have been discussed by their parents about the harmful effects of junk foods over health. According to the research by scientists, it has been found that junk foods have negative effects on the health in many ways. They are generally fried food found in the market in the packets. They become high in calories, high in cholesterol, low in healthy nutrients, high in sodium mineral, high in sugar, starch, unhealthy fat, lack of protein and lack of dietary fibers. Processed and junk foods are the means of rapid and unhealthy weight gain and negatively impact the whole body throughout the life. It makes able a person to gain excessive weight which is called as obesity. Junk foods tastes good and looks good however do not fulfil the healthy calorie requirement of the body. Some of the foods like french fries, fried foods, pizza, burgers, candy, soft drinks, baked goods, ice cream, cookies, etc are the example of high-sugar and high-fat containing foods. It is found according to the Centres for Disease Control and Prevention that Kids and children eating junk food are more prone to the type-2 diabetes. In type-2 diabetes our body become unable to regulate blood sugar level. Risk of getting this disease is increasing as one become more obese or overweight. It increases the risk of kidney failure. Eating junk food daily lead us to the nutritional deficiencies in the body because it is lack of essential nutrients, vitamins, iron, minerals and dietary fibers. It increases risk of cardiovascular diseases because it is rich in saturated fat, sodium and bad cholesterol. High sodium and bad cholesterol diet increases blood pressure and overloads the heart functioning. One who like junk food develop more risk to put on extra weight and become fatter and unhealthier. Junk foods contain high level carbohydrate which spike blood sugar level and make person more lethargic, sleepy and less active and alert. Reflexes and senses of the people eating this food become dull day by day thus they live more sedentary life. Junk foods are the source of constipation and other disease like diabetes, heart ailments, clogged arteries, heart attack, strokes, etc because of being poor in nutrition. Junk food is the easiest way to gain unhealthy weight. The amount of fats and sugar in the food makes you gain weight rapidly. However, this is not a healthy weight. It is more of fats and cholesterol which will have a harmful impact on your health. Junk food is also one of the main reasons for the increase in obesity nowadays.This food only looks and tastes good, other than that, it has no positive points. The amount of calorie your body requires to stay fit is not fulfilled by this food. For instance, foods like French fries, burgers, candy, and cookies, all have high amounts of sugar and fats. Therefore, this can result in long-term illnesses like diabetes and high blood pressure. This may also result in kidney failure. Above all, you can get various nutritional deficiencies when you don’t consume the essential nutrients, vitamins, minerals and more. You become prone to cardiovascular diseases due to the consumption of bad cholesterol and fat plus sodium. In other words, all this interferes with the functioning of your heart. Furthermore, junk food contains a higher level of carbohydrates. It will instantly spike your blood sugar levels. This will result in lethargy, inactiveness, and sleepiness. A person reflex becomes dull overtime and they lead an inactive life. To make things worse, junk food also clogs your arteries and increases the risk of a heart attack. Therefore, it must be avoided at the first instance to save your life from becoming ruined.The main problem with junk food is that people don’t realize its ill effects now. When the time comes, it is too late. Most importantly, the issue is that it does not impact you instantly. It works on your overtime; you will face the consequences sooner or later. Thus, it is better to stop now.You can avoid junk food by encouraging your children from an early age to eat green vegetables. Their taste buds must be developed as such that they find healthy food tasty. Moreover, try to mix things up. Do not serve the same green vegetable daily in the same style. Incorporate different types of healthy food in their diet following different recipes. This will help them to try foods at home rather than being attracted to junk food.In short, do not deprive them completely of it as that will not help. Children will find one way or the other to have it. Make sure you give them junk food in limited quantities and at healthy periods of time. '

In [29]:
print(lexrank(test_text, 8))

 Junk foods tastes good and looks good however do not fulfil the healthy calorie requirement of the body. It is found according to the Centres for Disease Control and Prevention that Kids and children eating junk food are more prone to the type-2 diabetes. The amount of fats and sugar in the food makes you gain weight rapidly. However, this is not a healthy weight. It is more of fats and cholesterol which will have a harmful impact on your health. To make things worse, junk food also clogs your arteries and increases the risk of a heart attack. This will help them to try foods at home rather than being attracted to junk food.In short, do not deprive them completely of it as that will not help. Children will find one way or the other to have it.


# Bart

In [ ]:
### run this cell at first time
### Bart requires the PyTorch library, you can use Anaconda to install one that matches your environment
# !pip install transformers

In [8]:
from transformers import BartForConditionalGeneration, BartTokenizer, BartConfig

In [9]:
tokenizer = BartTokenizer.from_pretrained('facebook/bart-large-cnn')
model = BartForConditionalGeneration.from_pretrained('facebook/bart-large-cnn')

In [26]:
def bart(text):
    inputs = tokenizer.batch_encode_plus([text], max_length=1024, return_tensors='pt', truncation=True)
    summary_ids = model.generate(inputs['input_ids'], early_stopping=True, min_length = 200)
    bart_summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return bart_summary

In [27]:
test_text='Junk foods taste good that’s why it is mostly liked by everyone of any age group especially kids and school going children. They generally ask for the junk food daily because they have been trend so by their parents from the childhood. They never have been discussed by their parents about the harmful effects of junk foods over health. According to the research by scientists, it has been found that junk foods have negative effects on the health in many ways. They are generally fried food found in the market in the packets. They become high in calories, high in cholesterol, low in healthy nutrients, high in sodium mineral, high in sugar, starch, unhealthy fat, lack of protein and lack of dietary fibers. Processed and junk foods are the means of rapid and unhealthy weight gain and negatively impact the whole body throughout the life. It makes able a person to gain excessive weight which is called as obesity. Junk foods tastes good and looks good however do not fulfil the healthy calorie requirement of the body. Some of the foods like french fries, fried foods, pizza, burgers, candy, soft drinks, baked goods, ice cream, cookies, etc are the example of high-sugar and high-fat containing foods. It is found according to the Centres for Disease Control and Prevention that Kids and children eating junk food are more prone to the type-2 diabetes. In type-2 diabetes our body become unable to regulate blood sugar level. Risk of getting this disease is increasing as one become more obese or overweight. It increases the risk of kidney failure. Eating junk food daily lead us to the nutritional deficiencies in the body because it is lack of essential nutrients, vitamins, iron, minerals and dietary fibers. It increases risk of cardiovascular diseases because it is rich in saturated fat, sodium and bad cholesterol. High sodium and bad cholesterol diet increases blood pressure and overloads the heart functioning. One who like junk food develop more risk to put on extra weight and become fatter and unhealthier. Junk foods contain high level carbohydrate which spike blood sugar level and make person more lethargic, sleepy and less active and alert. Reflexes and senses of the people eating this food become dull day by day thus they live more sedentary life. Junk foods are the source of constipation and other disease like diabetes, heart ailments, clogged arteries, heart attack, strokes, etc because of being poor in nutrition. Junk food is the easiest way to gain unhealthy weight. The amount of fats and sugar in the food makes you gain weight rapidly. However, this is not a healthy weight. It is more of fats and cholesterol which will have a harmful impact on your health. Junk food is also one of the main reasons for the increase in obesity nowadays.This food only looks and tastes good, other than that, it has no positive points. The amount of calorie your body requires to stay fit is not fulfilled by this food. For instance, foods like French fries, burgers, candy, and cookies, all have high amounts of sugar and fats. Therefore, this can result in long-term illnesses like diabetes and high blood pressure. This may also result in kidney failure. Above all, you can get various nutritional deficiencies when you don’t consume the essential nutrients, vitamins, minerals and more. You become prone to cardiovascular diseases due to the consumption of bad cholesterol and fat plus sodium. In other words, all this interferes with the functioning of your heart. Furthermore, junk food contains a higher level of carbohydrates. It will instantly spike your blood sugar levels. This will result in lethargy, inactiveness, and sleepiness. A person reflex becomes dull overtime and they lead an inactive life. To make things worse, junk food also clogs your arteries and increases the risk of a heart attack. Therefore, it must be avoided at the first instance to save your life from becoming ruined.The main problem with junk food is that people don’t realize its ill effects now. When the time comes, it is too late. Most importantly, the issue is that it does not impact you instantly. It works on your overtime; you will face the consequences sooner or later. Thus, it is better to stop now.You can avoid junk food by encouraging your children from an early age to eat green vegetables. Their taste buds must be developed as such that they find healthy food tasty. Moreover, try to mix things up. Do not serve the same green vegetable daily in the same style. Incorporate different types of healthy food in their diet following different recipes. This will help them to try foods at home rather than being attracted to junk food.In short, do not deprive them completely of it as that will not help. Children will find one way or the other to have it. Make sure you give them junk food in limited quantities and at healthy periods of time. '

In [28]:
print(bart(test_text))

Junk foods taste good that’s why it is mostly liked by everyone of any age group especially kids and school going children. They generally ask for the junk food daily because they have been trend so by their parents from the childhood. According to the research by scientists, it has been found that junk foods have negative effects on the health in many ways. They are generally fried food found in the market in the packets. They become high in calories, high in cholesterol, low in healthy nutrients and high in sodium mineral. They also contain sugar, starch, unhealthy fat, lack of protein and lack of dietary fibers. Kids and children eating junk food are more prone to the type-2 diabetes


# ROUGE

In [ ]:
### run this cell at first time
# !pip install rouge

In [30]:
from rouge import Rouge

In [31]:
def rouge_score(t1, t2):
    # t1, t2: generated text and original text
    my_rouge = Rouge()
    score = my_rouge.get_scores(t1, t2)
    rouge_1 = score[0]['rouge-1']['r']
    rouge_2 = score[0]['rouge-2']['r']
    rouge_l = score[0]['rouge-l']['r']
    
    return [rouge_1, rouge_2, rouge_l]

In [ ]:
t1 = lexrank(test_text, 10)
t2 = bart(test_text)

In [ ]:
rouge_score(t1, t2)

# Combination

### Workflow

**Input:** (bodytext, related work section) <br><br>
**->** (generated related work section, related work section) <br><br>
**Output:** ROUGE score

In [32]:
def generate_score(bodytext, rwtext, n=5):
    # bodytext: bodytext of the paper except related work section
    # rwtext: related work section
    # n: number of sentences for lexrank algorithm, default = 5
    
    lexrank_res = lexrank(bodytext, n)
    bart_res = bart(bodytext)
    
    lexrank_score = rouge_score(lexrank_res, rwtext)
    bart_score = rouge_score(bart_res, rwtext)
    
    return {'LexRank': lexrank_score, 'Bart': bart_score}

# Use body text to generate related work section

In [42]:
lexrank_scorel = []
bart_scorel = []

k = 0

for i in data_sample.index:
    rwtext = data_sample.at[i, 'related_work_text']
    bodytext = data_sample.at[i, 'body_text']
    score = generate_score(bodytext, rwtext, 8)
    
    lexrank_scorel.append(score['LexRank'])
    bart_scorel.append(score['Bart'])
    
    k = k + 1
    
    if k%10 == 0:
        print(k, 'samples done!')

10 samples done!
20 samples done!
30 samples done!
40 samples done!
50 samples done!
60 samples done!
70 samples done!
80 samples done!
90 samples done!
100 samples done!
110 samples done!
120 samples done!
130 samples done!
140 samples done!
150 samples done!
160 samples done!
170 samples done!
180 samples done!
190 samples done!
200 samples done!
210 samples done!
220 samples done!


In [43]:
np.array(lexrank_scorel).mean(axis=0)

array([0.22420388, 0.05813858, 0.20297181])

In [44]:
np.array(bart_scorel).mean(axis=0)

array([0.1198745 , 0.02390298, 0.11110143])

# Use abstract to generate related work section

In [57]:
lexrank_scorel_1 = []
bart_scorel_1 = []

k = 0

for i in data_sample.index:
    rwtext = data_sample.at[i, 'related_work_text']
    abstract = data_sample.at[i, 'abstract']
    if len(abstract) > 500:
        score = generate_score(abstract, rwtext, 8)
        lexrank_scorel_1.append(score['LexRank'])
        bart_scorel_1.append(score['Bart'])
    
    k = k + 1
    
    if k%10 == 0:
        print(k, 'samples done!')

10 samples done!
20 samples done!
30 samples done!
40 samples done!
50 samples done!
60 samples done!
70 samples done!
80 samples done!
90 samples done!
100 samples done!
110 samples done!
120 samples done!
130 samples done!
140 samples done!
150 samples done!
160 samples done!
170 samples done!
180 samples done!
190 samples done!
200 samples done!
210 samples done!
220 samples done!


In [58]:
np.array(lexrank_scorel_1).mean(axis=0)

array([0.14780519, 0.03266594, 0.13481983])

In [59]:
np.array(bart_scorel_1).mean(axis=0)

array([0.11945076, 0.0236271 , 0.1105354 ])